# Day 1 - April 22, 2020

### Pandas Dataframe

In [2]:
import pandas as pd
import numpy as np
from IPython.core.display import Image

In [3]:
ls "D:\Learning Data Science\Python - Pandas\Pandas cookbook\Pandas-Cookbook-master\data"

 Volume in drive D is Data
 Volume Serial Number is 4E50-31E2

 Directory of D:\Learning Data Science\Python - Pandas\Pandas cookbook\Pandas-Cookbook-master\data

12/11/2019  09:49 AM    <DIR>          .
12/11/2019  09:49 AM    <DIR>          ..
12/11/2019  09:49 AM            75,869 aapl_stock.csv
12/11/2019  09:49 AM            87,672 amzn_stock.csv
12/11/2019  09:49 AM    <DIR>          backup
12/11/2019  09:49 AM             1,468 baseball14.csv
12/11/2019  09:49 AM             1,402 baseball15.csv
12/11/2019  09:49 AM             1,481 baseball16.csv
12/11/2019  09:49 AM           884,736 chinook.db
12/11/2019  09:49 AM         1,252,058 college.csv
12/11/2019  09:49 AM             1,028 college_data_dictionary.csv
12/11/2019  09:49 AM               514 college_diversity.csv
12/11/2019  09:49 AM        32,165,563 crime.h5
12/11/2019  09:49 AM             1,360 denver_neigh_pop.csv
12/11/2019  09:49 AM            60,303 denver_neighborhood_pop.csv
12/11/2019  09:49 AM                88 denver_pop.csv
12/11/2019  09:49 AM    <DIR>          descriptions
12/11/2019  09:49 AM         2,571,905 diamonds.csv
12/11/2019  09:49 AM           243,245 employee.csv
12/11/2019  09:49 AM         2,989,130 flights.csv
12/11/2019  09:49 AM               184 food_prices.csv
12/11/2019  09:49 AM               113 food_transactions.csv
12/11/2019  09:49 AM    <DIR>          gas prices
12/11/2019  09:49 AM           441,043 meetup_groups.csv
12/11/2019  09:49 AM         1,545,051 movie.csv
12/11/2019  09:49 AM           552,170 movie_altered.csv
12/11/2019  09:49 AM                48 names.csv
12/11/2019  09:49 AM            36,612 restaurant_inspections.csv
12/11/2019  09:49 AM               234 sensors.csv
12/11/2019  09:49 AM            81,289 slb_stock.csv
12/11/2019  09:49 AM               104 stackme.csv
12/11/2019  09:49 AM                68 state_fruit.csv
12/11/2019  09:49 AM                73 state_fruit2.csv
12/11/2019  09:49 AM                65 stocks_2016.csv
12/11/2019  09:49 AM               108 stocks_2017.csv
12/11/2019  09:49 AM                71 stocks_2018.csv
12/11/2019  09:49 AM               120 texas_cities.csv
12/11/2019  09:49 AM               631 weight_loss.csv
12/11/2019  09:49 AM               437 weightlifting.csv
12/11/2019  09:49 AM               437 weightlifting_men.csv
12/11/2019  09:49 AM               396 weightlifting_women.csv
              36 File(s)     42,997,076 bytes
               5 Dir(s)  70,278,029,312 bytes free

In [4]:
movie = pd.read_csv("D:\Learning Data Science\Python - Pandas\Pandas cookbook\Pandas-Cookbook-master\data\movie.csv")

In [5]:
movie.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [6]:
movie

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [7]:
movie.tail()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [8]:
# pulls out the index, columns, and the data of the DataFrame into their own variables
columns = movie.columns

columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [9]:
index = movie.index

index

RangeIndex(start=0, stop=4916, step=1)

In [11]:
data = movie.to_numpy()

data

array([['Color', 'James Cameron', 723.0, ..., 7.9, 1.78, 33000],
       ['Color', 'Gore Verbinski', 302.0, ..., 7.1, 2.35, 0],
       ['Color', 'Sam Mendes', 602.0, ..., 6.8, 2.35, 85000],
       ...,
       ['Color', 'Benjamin Roberds', 13.0, ..., 6.3, nan, 16],
       ['Color', 'Daniel Hsia', 14.0, ..., 6.3, 2.35, 660],
       ['Color', 'Jon Gunn', 43.0, ..., 6.6, 1.85, 456]], dtype=object)

In [12]:
# Output the Python type of each DataFrame component
type(columns)

pandas.core.indexes.base.Index

In [13]:
type(index)

pandas.core.indexes.range.RangeIndex

In [14]:
type(data)

numpy.ndarray

In [15]:
columns.to_numpy()

array(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes',
       'actor_2_name', 'actor_1_facebook_likes', 'gross', 'genres',
       'actor_1_name', 'movie_title', 'num_voted_users',
       'cast_total_facebook_likes', 'actor_3_name',
       'facenumber_in_poster', 'plot_keywords', 'movie_imdb_link',
       'num_user_for_reviews', 'language', 'country', 'content_rating',
       'budget', 'title_year', 'actor_2_facebook_likes', 'imdb_score',
       'aspect_ratio', 'movie_facebook_likes'], dtype=object)

In [16]:
index.to_numpy()

array([   0,    1,    2, ..., 4913, 4914, 4915], dtype=int64)

In [17]:
"""common pandas data types:
f float â€“ The NumPy float type, which supports missing values
f int â€“ The NumPy integer type, which does not support missing values
f 'Int64' â€“ pandas nullable integer type
f object â€“ The NumPy type for storing strings (and mixed types)
f 'category' â€“ pandas categorical type, which does support missing values
f bool â€“ The NumPy Boolean type, which does not support missing values (None
becomes False, np.nan becomes True)
f 'boolean' â€“ pandas nullable Boolean type
f datetime64[ns] â€“ The NumPy date type, which does support missing values (NaT)"""

# display the data type of each column in a DataFrame
movie.dtypes

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

In [18]:
movie.dtypes.value_counts()

float64    13
object     12
int64       3
dtype: int64

In [19]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4916 entries, 0 to 4915
Data columns (total 28 columns):
color                        4897 non-null object
director_name                4814 non-null object
num_critic_for_reviews       4867 non-null float64
duration                     4901 non-null float64
director_facebook_likes      4814 non-null float64
actor_3_facebook_likes       4893 non-null float64
actor_2_name                 4903 non-null object
actor_1_facebook_likes       4909 non-null float64
gross                        4054 non-null float64
genres                       4916 non-null object
actor_1_name                 4909 non-null object
movie_title                  4916 non-null object
num_voted_users              4916 non-null int64
cast_total_facebook_likes    4916 non-null int64
actor_3_name                 4893 non-null object
facenumber_in_poster         4903 non-null float64
plot_keywords                4764 non-null object
movie_imdb_link              4916 non-null object
num_user_for_reviews         4895 non-null float64
language                     4904 non-null object
country                      4911 non-null object
content_rating               4616 non-null object
budget                       4432 non-null float64
title_year                   4810 non-null float64
actor_2_facebook_likes       4903 non-null float64
imdb_score                   4916 non-null float64
aspect_ratio                 4590 non-null float64
movie_facebook_likes         4916 non-null int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [20]:
movie.color.value_counts()

Color              4693
Black and White     204
Name: color, dtype: int64

# Day 2 - April 23, 2020

### Selecting a Column

In [21]:
movie["director_name"]

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...
4911          Scott Smith
4912                  NaN
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: object

In [22]:
movie.director_name

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...
4911          Scott Smith
4912                  NaN
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: object

In [23]:
movie.loc[:,'director_name']

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...
4911          Scott Smith
4912                  NaN
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: object

In [24]:
movie.iloc[:,1]

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...
4911          Scott Smith
4912                  NaN
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: object

In [25]:
movie["director_name"].index

RangeIndex(start=0, stop=4916, step=1)

In [26]:
movie["director_name"].dtype

dtype('O')

In [27]:
movie["director_name"].size

4916

In [28]:
movie["director_name"].name

'director_name'

In [29]:
type(movie["director_name"])

pandas.core.series.Series

In [30]:
movie["director_name"].apply(type).unique()

array([<class 'str'>, <class 'float'>], dtype=object)

# Day 3 - April 24, 2020

### Calling Series methods

In [31]:
s_attr_methods = set(dir(pd.Series))
len(s_attr_methods)

465

In [32]:
df_attr_methods = set(dir(pd.DataFrame))
len(df_attr_methods)

451

In [33]:
len(s_attr_methods & df_attr_methods)

394

In [34]:
director = movie["director_name"]
director.dtype

dtype('O')

In [35]:
fb_likes = movie["actor_1_facebook_likes"]
fb_likes.dtype

dtype('float64')

In [36]:
director.head()

0        James Cameron
1       Gore Verbinski
2           Sam Mendes
3    Christopher Nolan
4          Doug Walker
Name: director_name, dtype: object

In [37]:
director.sample(n=5)

1270       Martin Scorsese
4417             Jeff Burr
1875    George P. Cosmatos
3446          Kevin Brodie
1507       Justin Chadwick
Name: director_name, dtype: object

In [38]:
fb_likes.head()

0     1000.0
1    40000.0
2    11000.0
3    27000.0
4      131.0
Name: actor_1_facebook_likes, dtype: float64

In [39]:
director.value_counts()

Steven Spielberg      26
Woody Allen           22
Clint Eastwood        20
Martin Scorsese       20
Ridley Scott          16
                      ..
Rob McKittrick         1
Dror Moreh             1
Julien Temple          1
Wallace Wolodarsky     1
Brandon Camp           1
Name: director_name, Length: 2397, dtype: int64

In [40]:
director.value_counts(normalize=True)

Steven Spielberg      0.005401
Woody Allen           0.004570
Clint Eastwood        0.004155
Martin Scorsese       0.004155
Ridley Scott          0.003324
                        ...
Rob McKittrick        0.000208
Dror Moreh            0.000208
Julien Temple         0.000208
Wallace Wolodarsky    0.000208
Brandon Camp          0.000208
Name: director_name, Length: 2397, dtype: float64

In [41]:
fb_likes.value_counts()

1000.0     436
11000.0    206
2000.0     189
3000.0     150
12000.0    131
          ...
362.0        1
216.0        1
859.0        1
225.0        1
334.0        1
Name: actor_1_facebook_likes, Length: 877, dtype: int64

In [42]:
director.size

4916

In [43]:
director.shape

(4916,)

In [44]:
len(director)

4916

In [45]:
director.unique()

array(['James Cameron', 'Gore Verbinski', 'Sam Mendes', ...,
       'Scott Smith', 'Benjamin Roberds', 'Daniel Hsia'], dtype=object)

In [46]:
len(director.unique())

2398

In [47]:
director.count()

4814

In [48]:
director.hasnans

True

In [49]:
director.isna()

0       False
1       False
2       False
3       False
4       False
        ...
4911    False
4912     True
4913    False
4914    False
4915    False
Name: director_name, Length: 4916, dtype: bool

In [50]:
director.notna()

0        True
1        True
2        True
3        True
4        True
        ...
4911     True
4912    False
4913     True
4914     True
4915     True
Name: director_name, Length: 4916, dtype: bool

In [51]:
director.describe()

count                 4814
unique                2397
top       Steven Spielberg
freq                    26
Name: director_name, dtype: object

In [52]:
fb_likes.size

4916

In [53]:
fb_likes.count()

4909

In [54]:
fb_likes_filled = fb_likes.fillna(0)
fb_likes_filled.size

4916

In [55]:
fb_likes_dropped = fb_likes.dropna()
fb_likes_dropped.size

4909

In [56]:
fb_likes.min()

0.0

In [57]:
fb_likes.max()

640000.0

In [58]:
fb_likes.mean()

6494.488490527602

In [59]:
fb_likes.median()

982.0

In [60]:
fb_likes.std()

15106.986883848309

In [61]:
fb_likes.describe()

count      4909.000000
mean       6494.488491
std       15106.986884
min           0.000000
25%         607.000000
50%         982.000000
75%       11000.000000
max      640000.000000
Name: actor_1_facebook_likes, dtype: float64

In [62]:
fb_likes.quantile(0.2)

510.0

In [63]:
fb_likes.quantile([0,0.2,0.4,0.6,0.8])

0.0        0.0
0.2      510.0
0.4      854.0
0.6     1000.0
0.8    13000.0
Name: actor_1_facebook_likes, dtype: float64

# Day 4 - April 25, 2020

### Series Operations

In [64]:
imdb_score = movie["imdb_score"]

In [65]:
imdb_score

0       7.9
1       7.1
2       6.8
3       8.5
4       7.1
       ...
4911    7.7
4912    7.5
4913    6.3
4914    6.3
4915    6.6
Name: imdb_score, Length: 4916, dtype: float64

In [66]:
imdb_score + 1

0       8.9
1       8.1
2       7.8
3       9.5
4       8.1
       ...
4911    8.7
4912    8.5
4913    7.3
4914    7.3
4915    7.6
Name: imdb_score, Length: 4916, dtype: float64

In [67]:
imdb_score * 2.5

0       19.75
1       17.75
2       17.00
3       21.25
4       17.75
        ...
4911    19.25
4912    18.75
4913    15.75
4914    15.75
4915    16.50
Name: imdb_score, Length: 4916, dtype: float64

In [68]:
imdb_score / 2

0       3.95
1       3.55
2       3.40
3       4.25
4       3.55
        ...
4911    3.85
4912    3.75
4913    3.15
4914    3.15
4915    3.30
Name: imdb_score, Length: 4916, dtype: float64

In [69]:
imdb_score // 7

0       1.0
1       1.0
2       0.0
3       1.0
4       1.0
       ...
4911    1.0
4912    1.0
4913    0.0
4914    0.0
4915    0.0
Name: imdb_score, Length: 4916, dtype: float64

In [70]:
imdb_score % 2

0       1.9
1       1.1
2       0.8
3       0.5
4       1.1
       ...
4911    1.7
4912    1.5
4913    0.3
4914    0.3
4915    0.6
Name: imdb_score, Length: 4916, dtype: float64

In [71]:
# comparison operators- (>),(<),(>=),(<=),(==),(!=)
imdb_score>7

0        True
1        True
2       False
3        True
4        True
        ...
4911     True
4912     True
4913    False
4914    False
4915    False
Name: imdb_score, Length: 4916, dtype: bool

In [72]:
director == "James Cameron"

0        True
1       False
2       False
3       False
4       False
        ...
4911    False
4912    False
4913    False
4914    False
4915    False
Name: director_name, Length: 4916, dtype: bool

In [73]:
imdb_score.add(1)      # imdb_score+1

0       8.9
1       8.1
2       7.8
3       9.5
4       8.1
       ...
4911    8.7
4912    8.5
4913    7.3
4914    7.3
4915    7.6
Name: imdb_score, Length: 4916, dtype: float64

In [74]:
imdb_score.gt(7)      #imdb_score > 7

0        True
1        True
2       False
3        True
4        True
        ...
4911     True
4912     True
4913    False
4914    False
4915    False
Name: imdb_score, Length: 4916, dtype: bool

In [75]:
money = pd.Series([100, 20, None])

In [76]:
money

0    100.0
1     20.0
2      NaN
dtype: float64

In [77]:
money - 15

0    85.0
1     5.0
2     NaN
dtype: float64

In [78]:
money.sub(15, fill_value=0) # money - 15 with substituting 0 for null values

0    85.0
1     5.0
2   -15.0
dtype: float64

### Chaining Series Methods

In [79]:
director.value_counts().head(3)

Steven Spielberg    26
Woody Allen         22
Clint Eastwood      20
Name: director_name, dtype: int64

In [80]:
movie.head(3).T

,0,1,2
color,Color,Color,Color
director_name,James Cameron,Gore Verbinski,Sam Mendes
num_critic_for_reviews,723,302,602
duration,178,169,148
director_facebook_likes,0,563,0
actor_3_facebook_likes,855,1000,161
actor_2_name,Joel David Moore,Orlando Bloom,Rory Kinnear
actor_1_facebook_likes,1000,40000,11000
gross,7.60506e+08,3.09404e+08,2.00074e+08
genres,Action|Adventure|Fantasy|Sci-Fi,Action|Adventure|Fantasy,Action|Adventure|Thriller
actor_1_name,CCH Pounder,Johnny Depp,Christoph Waltz
movie_title,Avatar,Pirates of the Caribbean: At World's End,Spectre
num_voted_users,886204,471220,275868
cast_total_facebook_likes,4834,48350,11700
actor_3_name,Wes Studi,Jack Davenport,Stephanie Sigman
facenumber_in_poster,0,0,1
plot_keywords,avatar|future|marine|native|paraplegic,goddess|marriage ceremony|marriage proposal|pi...,bomb|espionage|sequel|spy|terrorist
movie_imdb_link,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,http://www.imdb.com/title/tt2379713/?ref_=fn_t...
num_user_for_reviews,3054,1238,994
language,English,English,English
country,USA,USA,UK
content_rating,PG-13,PG-13,PG-13
budget,2.37e+08,3e+08,2.45e+08
title_year,2009,2007,2015
actor_2_facebook_likes,936,5000,393
imdb_score,7.9,7.1,6.8
aspect_ratio,1.78,2.35,2.35
movie_facebook_likes,33000,0,85000

In [81]:
fb_likes.isna().sum()      #counting the number of missing values

7

In [82]:
fb_likes.dtype

dtype('float64')

In [83]:
fb_likes.fillna(0).astype(int).head()

0     1000
1    40000
2    11000
3    27000
4      131
Name: actor_1_facebook_likes, dtype: int32

In [84]:
"""Another option for debugging chains (other than stepwise incremental execution) is to call the .pipe method to show an 
intermediate value. The .pipe method on a Series needs to be passed a function that accepts a Series as input and can 
return anything (but we want to return a Series if we want to use it in a method chain)."""

def debug_ser(ser):
    print ("BEFORE")
    print (ser)
    print ("AFTER")
    return (ser)

In [85]:
fb_likes.fillna(0).pipe(debug_ser).astype(int).head()

BEFORE
0        1000.0
1       40000.0
2       11000.0
3       27000.0
4         131.0
         ...
4911      637.0
4912      841.0
4913        0.0
4914      946.0
4915       86.0
Name: actor_1_facebook_likes, Length: 4916, dtype: float64
AFTER

0     1000
1    40000
2    11000
3    27000
4      131
Name: actor_1_facebook_likes, dtype: int32

In [86]:
(
    fb_likes
    .fillna(0)
    .astype(int)
    .head()
)

0     1000
1    40000
2    11000
3    27000
4      131
Name: actor_1_facebook_likes, dtype: int32

In [87]:
fb_likes \
.fillna(0) \
.astype(int) \
.head()

0     1000
1    40000
2    11000
3    27000
4      131
Name: actor_1_facebook_likes, dtype: int32

# Day 5 - April 26, 2020

### Renaming columns names

In [ ]:
# Option 1 - First create a dictionary that maps old column names to new ones and then pass the dictionary to the rename method

In [91]:
col_map = {
    "director_name" : "director",
    "num_critic_for_reviews" : "critic_reviews"
}
movie.rename(columns=col_map)

,color,director,critic_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [92]:
movie.head(3).T

,0,1,2
color,Color,Color,Color
director_name,James Cameron,Gore Verbinski,Sam Mendes
num_critic_for_reviews,723,302,602
duration,178,169,148
director_facebook_likes,0,563,0
actor_3_facebook_likes,855,1000,161
actor_2_name,Joel David Moore,Orlando Bloom,Rory Kinnear
actor_1_facebook_likes,1000,40000,11000
gross,7.60506e+08,3.09404e+08,2.00074e+08
genres,Action|Adventure|Fantasy|Sci-Fi,Action|Adventure|Fantasy,Action|Adventure|Thriller
actor_1_name,CCH Pounder,Johnny Depp,Christoph Waltz
movie_title,Avatar,Pirates of the Caribbean: At World's End,Spectre
num_voted_users,886204,471220,275868
cast_total_facebook_likes,4834,48350,11700
actor_3_name,Wes Studi,Jack Davenport,Stephanie Sigman
facenumber_in_poster,0,0,1
plot_keywords,avatar|future|marine|native|paraplegic,goddess|marriage ceremony|marriage proposal|pi...,bomb|espionage|sequel|spy|terrorist
movie_imdb_link,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,http://www.imdb.com/title/tt2379713/?ref_=fn_t...
num_user_for_reviews,3054,1238,994
language,English,English,English
country,USA,USA,UK
content_rating,PG-13,PG-13,PG-13
budget,2.37e+08,3e+08,2.45e+08
title_year,2009,2007,2015
actor_2_facebook_likes,936,5000,393
imdb_score,7.9,7.1,6.8
aspect_ratio,1.78,2.35,2.35
movie_facebook_likes,33000,0,85000

In [93]:
# renaming index - setting index to movie title column and changing some index values

idx_map = {
    "Avatar" : "Rattva",
    "Spectre" : "Ertceps",
    "Pirates of the Caribbean: At World's End" : "POC"
}

col_map = {
    "aspect_ratio" : "aspect",
    "movie_facebook_likes" : "fblikes"
}


(
    movie.set_index("movie_title")
    .rename(index = idx_map, columns = col_map)
    .head(5)
)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect,fblikes
movie_title,,,,,,,,,,,,,,,,,,,,,
Rattva,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
POC,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
Ertceps,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
The Dark Knight Rises,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
Star Wars: Episode VII - The Force Awakens,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [94]:
# Option 2 - reassign the index and column attributes to a Python list, make needed changes and assign to index and column names
# Option 3 - read a column as the index

movies = pd.read_csv("D:\Learning Data Science\Python - Pandas\Pandas cookbook\Pandas-Cookbook-master\data\movie.csv",
                     index_col = "movie_title") # reading data as movies
ids = movies.index.to_list()
columns = movies.columns.to_list()
ids[1] = "POC"
columns[1] = "director"
columns[-1] = "fblikes"
movies.index = ids
movies.columns = columns
movies.head(3)

,color,director,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,fblikes
Avatar,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
POC,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
Spectre,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000

In [95]:
# Option 4 - pass a function in the rename method, e.g. to clean up column names

def to_clean(val):
    return val.strip().lower().replace(" ","_")

movies.rename(columns=to_clean).head(3)

,color,director,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,fblikes
Avatar,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
POC,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
Spectre,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000

In [96]:
# Option 5 - use list comprehensions to clean up column names

cols = [col.strip().lower().replace(" ","_") for col in movies.columns]
movies.columns = cols
movies.head()

,color,director,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,fblikes
Avatar,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
POC,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
Spectre,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
The Dark Knight Rises,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
Star Wars: Episode VII - The Force Awakens,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

# Day 6 - April 27, 2020

### Creating and deleting columns

In [97]:
# Option 1 - good for chaining
movies = pd.read_csv("D:\Learning Data Science\Python - Pandas\Pandas cookbook\Pandas-Cookbook-master\data\movie.csv")
movies["has_seen"] = 0
movies.head(3)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,has_seen
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,0
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,0

In [98]:
# Option 2 - assign method
movies = pd.read_csv("D:\Learning Data Science\Python - Pandas\Pandas cookbook\Pandas-Cookbook-master\data\movie.csv")
movies.assign(has_seen=0)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,has_seen
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,0
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,0
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000,0
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84,0
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000,0
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16,0
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660,0
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456,0

In [99]:
# one way to add existing column values
total = movies.actor_1_facebook_likes + movies.actor_2_facebook_likes + movies.actor_3_facebook_likes + movie.director_facebook_likes

total.head()

0     2791.0
1    46563.0
2    11554.0
3    95000.0
4        NaN
dtype: float64

In [100]:
# another way to add existing column values
cols = [
    "actor_1_facebook_likes",
    "actor_2_facebook_likes",
    "actor_3_facebook_likes",
    "director_facebook_likes"
]
sum_col = movies.loc[:,cols].sum(axis="columns")
sum_col

0        2791.0
1       46563.0
2       11554.0
3       95000.0
4         274.0
         ...
4911     1427.0
4912     1753.0
4913        0.0
4914     2154.0
4915      141.0
Length: 4916, dtype: float64

In [101]:
movies.assign(total_likes = sum_col).head(5)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,total_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,2791.0
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,46563.0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,11554.0
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000,95000.0
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0,274.0

In [102]:
# pass in a function as the value of the parameter in the call to the .assign method
def sum_likes(df):
    return df[
        [
            c
            for c in df.columns
            if "like" in c
            and ("actor" in c or "director" in c)
        ]
    ].sum(axis=1)
movies.assign(total_likes=sum_likes).head(3).T

,0,1,2
color,Color,Color,Color
director_name,James Cameron,Gore Verbinski,Sam Mendes
num_critic_for_reviews,723,302,602
duration,178,169,148
director_facebook_likes,0,563,0
actor_3_facebook_likes,855,1000,161
actor_2_name,Joel David Moore,Orlando Bloom,Rory Kinnear
actor_1_facebook_likes,1000,40000,11000
gross,7.60506e+08,3.09404e+08,2.00074e+08
genres,Action|Adventure|Fantasy|Sci-Fi,Action|Adventure|Fantasy,Action|Adventure|Thriller
actor_1_name,CCH Pounder,Johnny Depp,Christoph Waltz
movie_title,Avatar,Pirates of the Caribbean: At World's End,Spectre
num_voted_users,886204,471220,275868
cast_total_facebook_likes,4834,48350,11700
actor_3_name,Wes Studi,Jack Davenport,Stephanie Sigman
facenumber_in_poster,0,0,1
plot_keywords,avatar|future|marine|native|paraplegic,goddess|marriage ceremony|marriage proposal|pi...,bomb|espionage|sequel|spy|terrorist
movie_imdb_link,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,http://www.imdb.com/title/tt2379713/?ref_=fn_t...
num_user_for_reviews,3054,1238,994
language,English,English,English
country,USA,USA,UK
content_rating,PG-13,PG-13,PG-13
budget,2.37e+08,3e+08,2.45e+08
title_year,2009,2007,2015
actor_2_facebook_likes,936,5000,393
imdb_score,7.9,7.1,6.8
aspect_ratio,1.78,2.35,2.35
movie_facebook_likes,33000,0,85000
total_likes,2791,46563,11554

In [103]:
# comparing total and sum_col
(
    movies.assign(total_likes = total)["total_likes"]
    .isna()
    .sum()
)

122

In [104]:
(
    movies.assign(total_likes = sum_col)["total_likes"]
    .isna()
    .sum()
)

0

In [105]:
# filling the missing values with 0
(
    movies.assign(total_likes = total.fillna(0))["total_likes"]
    .isna()
    .sum()
)

0

In [108]:
# checking if cast_total_facebook_likes is greater than or equal to total_likes

def cast_like_gt_actor (df):
    return (df["cast_total_facebook_likes"] >= df["total_likes"] )

df2 = movies.assign(total_likes=total,is_cast_likes_more=cast_like_gt_actor)

df2["is_cast_likes_more"].all()

# df2 = movies.assign(total_likes = total, is_cast_likes_more = (movies.cast_total_facebook_likes>=total))
# df2

False

In [109]:
#  drop column

df2 = df2.drop(columns="total_likes")

In [110]:
actor_sum = movies[
    [
        c
        for c in movies.columns
        if "actor_" in c and "_likes" in c
    ]
].sum(axis = "columns")

actor_sum

0        2791.0
1       46000.0
2       11554.0
3       73000.0
4         143.0
         ...
4911     1425.0
4912     1753.0
4913        0.0
4914     2154.0
4915      125.0
Length: 4916, dtype: float64

In [111]:
# calculate the percentage of the cast_total_facebook_likes that come from actor_sum

pct_like = actor_sum.div(movies["cast_total_facebook_likes"]).mul(100)

pct_like.describe()

count    4883.000000
mean       83.327889
std        14.056578
min        30.076696
25%        73.528368
50%        86.928884
75%        95.477440
max       100.000000
dtype: float64

In [113]:
pd.Series(pct_like.to_numpy(), index=movies["movie_title"]).head()

movie_title
Avatar                                         57.736864
Pirates of the Caribbean: At World's End       95.139607
Spectre                                        98.752137
The Dark Knight Rises                          68.378310
Star Wars: Episode VII - The Force Awakens    100.000000
dtype: float64

In [114]:
# insert a new column into a specific location in a DataFrame

profit_index = movies.columns.get_loc("gross") + 1
profit_index

9

In [115]:
movies.insert(loc=profit_index, column = "profit", value = movies["gross"] - movies["budget"])
movies.head(5)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,profit,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,523505847.0,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,9404152.0,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,-44925825.0,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,198130642.0,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [116]:
# one more way to delete a columns

del movies["director_name"]
movies.head(2).T

,0,1
color,Color,Color
num_critic_for_reviews,723,302
duration,178,169
director_facebook_likes,0,563
actor_3_facebook_likes,855,1000
actor_2_name,Joel David Moore,Orlando Bloom
actor_1_facebook_likes,1000,40000
gross,7.60506e+08,3.09404e+08
profit,5.23506e+08,9.40415e+06
genres,Action|Adventure|Fantasy|Sci-Fi,Action|Adventure|Fantasy
actor_1_name,CCH Pounder,Johnny Depp
movie_title,Avatar,Pirates of the Caribbean: At World's End
num_voted_users,886204,471220
cast_total_facebook_likes,4834,48350
actor_3_name,Wes Studi,Jack Davenport
facenumber_in_poster,0,0
plot_keywords,avatar|future|marine|native|paraplegic,goddess|marriage ceremony|marriage proposal|pi...
movie_imdb_link,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...
num_user_for_reviews,3054,1238
language,English,English
country,USA,USA
content_rating,PG-13,PG-13
budget,2.37e+08,3e+08
title_year,2009,2007
actor_2_facebook_likes,936,5000
imdb_score,7.9,7.1
aspect_ratio,1.78,2.35
movie_facebook_likes,33000,0

### End of Chapter 1